// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7x8dO_GOe8PY3BZxHc8RbUz_VS2p3f0o',
    appId: '1:603378864246:web:e7f2e36b0f9b1c51f84f57',
    messagingSenderId: '603378864246',
    projectId: 'chat-app-example-8d2fb',
    authDomain: 'chat-app-example-8d2fb.firebaseapp.com',
    storageBucket: 'chat-app-example-8d2fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7UbF1_h33_489WZ7S6bwR3-iQNszhUxE',
    appId: '1:603378864246:android:7ef8e97b2e619d80f84f57',
    messagingSenderId: '603378864246',
    projectId: 'chat-app-example-8d2fb',
    storageBucket: 'chat-app-example-8d2fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZm-36eA3W3t8a_EwveccQAcYO2c2dnpA',
    appId: '1:603378864246:ios:9e75c135bf523500f84f57',
    messagingSenderId: '603378864246',
    projectId: 'chat-app-example-8d2fb',
    storageBucket: 'chat-app-example-8d2fb.appspot.com',
    androidClientId: '603378864246-4la42olkghh4ltjs3merh0cic02eur3p.apps.googleusercontent.com',
    iosClientId: '603378864246-l9icb14fumtb44j5i45koljdo7h053s7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
